### ISSUE TITLE
Autosquash not triggered when the PR is validated

### ISSUE THREAD

**Issue by Kineolyan** [tibdex/autosquash#25] opened 2020-01-02 15:08 UTC
I have a personal repository where I mostly use PRs to run tests for me.
Therefore, every time I create a PR, I apply it the _autosquash_ label, to have it merge as soon as tests pass.
Currently, I see that this workflow does not get the PR merged as expected [1]. At the end of all checks, I can remove and set again the label. This time, as previous validations were ok, the action is triggered and the merge occurs.

I know it is not the initial goal of this action, but I can't see why it is not triggered, as it seems to be the purpose of the type "check_run:completed_.

[1] (https://github.com/Kineolyan/snow-hall/pull/7)
[2] (https://github.com/Kineolyan/snow-hall/pull/6/checks?check_run_id=370010823)

**Comment by tibdex** [comment] 2020-01-04 11:10
Seems related to https://github.com/tibdex/autosquash/issues/22#issuecomment-554751995 since your PR status is `blocked` too. You can [set the `ACTIONS_STEP_DEBUG` secret to `true`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/managing-a-workflow-run#enabling-step-debug-logging) in your repo and try to reproduce the issue to get more details about what event triggered the action and in which state your PR was at that time.

**Comment by tibdex** [comment] 2020-01-04 11:54
In fact the issue is that [checks created by GitHub Actions will not trigger workflows](https://github.community/t5/GitHub-Actions/on-check-run/m-p/35946/highlight/true#M2385) so Autosquash doesn't rerun after your [`build` action](https://github.com/Kineolyan/snow-hall/runs/371009252).

**Comment by Kineolyan** [comment] 2020-01-04 19:33
Thanks for the feedback. I'm watching the answer as you are. Feel free to close this issue if you want.

**Comment by Kineolyan** [comment] 2020-01-08 20:45
For the record, after switching the tests to CircleCI instead of one Github Action, it is working like a charm.

**Comment by boredland** [comment] 2020-02-27 13:57
hi! does this mean, currently the branches marked as "autosquash" aren't merged after the checks are green? thats a bummer...

**Comment by tibdex** [comment] 2020-02-27 14:04
Depends how your checks became green.
- If it was triggered by a GitHub Action, the Autosquash workflow won't execute as explained in https://github.com/tibdex/autosquash/issues/25#issuecomment-570779355.
- If it was triggered by an external action such as a successful CircleCI/Travis CI workflow, then the Autosquash workflow will execute as confirmed in https://github.com/tibdex/autosquash/issues/25#issuecomment-572249157.

**Comment by boredland** [comment] 2020-02-27 14:10
one of my checks is a github workflow (a ci pipeline). I wanted to merge as soon as all checks (including that one) are green.

**Comment by boredland** [comment] 2020-02-27 14:11
would it be possible to run the autosquash action on a schedule to come around that for now?

**Comment by tibdex** [comment] 2020-02-27 14:19
Yes [workflows can be scheduled](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#triggering-a-workflow-with-events). You could also try adding:

https://github.com/tibdex/autosquash/blob/3ded0d9e280d4dae06f2ebcdee1445e98820f006/.github/workflows/autosquash.yml#L30-L36

at the end of your existing GitHub CI workflow.

**Comment by boredland** [comment] 2020-02-27 14:32
thanks @tibdex ! But when I run it on a schedule, I get this totally different error: 
```##[error]Cannot destructure property `name` of 'undefined' or 'null'.```

So I'd guess you extract some information from the github event that isn't there on a schedule obviously. The github_token I have already set, but I think I doesn't help the situation, that another gh action marks green.

**Comment by boredland** [comment] 2020-02-27 16:17
totally overread that I should add that to the existing workflow! Makes sense, will try. Still think handling schedule-events would make sense.

**Closed as completed** 2020-04-11 20:39 UTC

**Comment by tibdex** [comment] 2020-04-11 20:46
You can use https://github.com/marketplace/actions/github-app-token as an often better workaround to `secrets.GITHUB_TOKEN`'s limitations than a personal access token.
